HW9 is completed
JokeTrue/otus-golang pull request #12
Opened 2020-05-24 16:02 UTC by JokeTrue

## Домашнее задание №9 «Генератор валидаторов»

### Критерии оценки
- Закоммичен сгенерированный код - 1 балл
- Пайплайн зелёный - 3 балла
- Добавлены новые юнит-тесты (доработаны имеющиеся) в `models` - до 2 баллов
- Добавлены юнит-тесты для тулзы в `govalidate` - до 2 баллов
- Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-05-30 06:49 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/88625/6760/

Здравствуйте!
Отличная работа, я бы лучше не написал.
Хорошо структурированный и логически связанный код.

Претензии к тестам и косметике.
6 / 10

Будет принято после обновления одного из тестовых файлов (см. комментарии).

2020-05-30 06:49 UTC, Antonboom commented on .golangci.yml
> +    - wsl
newline

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/test.sh
> +echo "PASS"
newline

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +
наблюдаются лишние нью-лайны

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +			Err: fmt.Errorf("expected length to be 32"),
хорошо бы в ошибке указать и актуальное значение.

\+ если форматных аргументов нет, используйте `errors.New`

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +			Err: fmt.Errorf("value is less then min"),
а какое значение? и какое min?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +			Err: fmt.Errorf("value is more than max"),
а какое значение? и какое max?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +	matched, err := regexp.MatchString("^\\w+@\\w+\\.\\w+$", u.Email)
FYI
в реальной тулзе скорее всего пришлось бы собирать пул регулярок и компилировать их заранее

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +			Field: "Addresses[i]",
можно конкретный индекс указать

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +			Err: fmt.Errorf("didnt pass regexp"),
больше информативности в ошибках!

или расширять FieldError соотв. полями

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +	allowedValues := []int{ 200,404,500 }
пробел после запятой, и убрать пробел у скобок

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_validation_generated.go
> +	passed := false
```
var passed bool
```
вкусовщина

`:=` используется для инициализации не zero-value значением

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_test.go
>  package models
обновите весь этот файл новым, и вставьте свой тест
https://github.com/OtusGolang/home_work/blob/master/hw09_generator_of_validators/models/models_test.go

а вообще хорошо бы было еще от себя добавить тестов

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/main.go
> +	flag.StringVar(&modelFilePath, "modelFilePath", "", "Path to file with model")
у какой-нибудь тулзы вы видели флаги в camelCase?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/main.go
> +var errorLogger = log.New(os.Stderr, "", 0)
чем это отличается от дефолтного логера от `log`?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/main.go
> +func main() {
структура main очень хорошая!

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/core/utils.go
> +package core
выглядит так, что бОльшая часть функций здесь должны быть неэкспортируемыми

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/models/models_test.go
> +		require.Len(t, errs, 3)
так тестировать нельзя
я думаю, вы понимаете почему?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/core/utils.go
> +		return fmt.Sprintf("[]%s", GetUnderlyingType(file, fieldType))
FYI: `"[]" + GetUnderlyingType(file, fieldType)`

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/core/utils.go
> +	baseName := path.Base(modelFilePath)
filepath

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/core/utils.go
> +	if Contains([]string{"int", "string"}, fieldType) {
вынести слайс в var?

2020-05-30 06:49 UTC, Antonboom commented on hw09_generator_of_validators/go-validate/core/parser_test.go
> +}
newline

2020-06-01 14:59 UTC, JokeTrue commented on hw09_generator_of_validators/go-validate/main.go
> +var errorLogger = log.New(os.Stderr, "", 0)
Отсутствием даты в начале строки лога

2020-06-03 05:14 UTC, Antonboom commented on hw09_generator_of_validators/models/models_test.go
> +func hasFieldErrors(errorsList []ValidationError, field string) bool {
👍

2020-06-03 05:14 UTC, Antonboom approved these changes
10 / 10

2020-06-03 05:19 UTC, merged