HW11 is completed
JokeTrue/otus-golang pull request #14
Opened 2020-05-26 18:43 UTC by JokeTrue

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-05-30 07:38 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/88625/6035/
Здравствуйте!

С `cancelFunc` вы пошли в правильном направлении.
Можно ли сделать еще чище и проще?
Можем вместе подумать.

6 / 10

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/telnet_test.go
> + 			err = client.Receive()
пробельчик? :)

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/telnet_test.go
> +	testing.Init()
а это зачем?

и почему не через `init()`?

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/test.sh
> +echo "PASS"
newline

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	err := c.execute(c.In, c.Connection)
FYI: можно `return c.execute(c.In, c.Connection)`

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	err := c.In.Close()
вы скорее должны закрывать Out?

а вообще предложил бы оставить только conn.close(), нужно ли брать на себя ответственность за In/Out?

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	Address    string
Эти поля точно должны быть все экспортируемыми?

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/main.go
> +			close(sigCh)
так можно панику поймать

предлагаю не закрывать sigCh, а делать `signal.Stop`

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	for {
зачем здесь цикл? (в 1 итерацию)

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/main.go
> +var timeout string
https://golang.org/pkg/flag/#Duration

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	for {
здесь зачем цикл?
вам нужно handler 1 раз запустить и по ошибке заканчивать работу тулзы, а вы в цикле гоняете

2020-05-30 07:38 UTC, Antonboom commented on hw11_telnet_client/main.go
> +func Worker(ctx context.Context, handler func() error, cancelFunc context.CancelFunc) {
приватный метод?
поместить за main

2020-06-01 16:08 UTC, JokeTrue commented on hw11_telnet_client/telnet_test.go
> +	testing.Init()
Без этой конструкции происходит следующая проблема при запуске тестов. Нашел это решение где-то на просторах StackOverflow.
```
flag provided but not defined: -test.v
Usage of /private/var/folders/_b/zxrhst9j2tv6br3_xb8zp8y40000gn/T/___telnet_test_go:
  -timeout string
    	connection timeout (default "10s")
```

2020-06-03 07:01 UTC, Antonboom approved these changes
Отлично, гораздо приятнее, чем раньше!
С флагом перемудрили

Принято
9 / 10

2020-06-03 07:01 UTC, Antonboom commented on hw11_telnet_client/telnet_test.go
> +	testing.Init()
потому что у вас `flag.Parse()` находится в init'e, что неправильно

на момент импорта пакетов никаких флагов понятное дело - нет

2020-06-03 07:01 UTC, Antonboom commented on hw11_telnet_client/telnet_test.go
> +	testing.Init()
https://golang.org/pkg/flag/
```
func main() {
	// All the interesting pieces are with the variables declared above, but
	// to enable the flag package to see the flags defined there, one must
	// execute, typically at the start of main (not init!):
	//	flag.Parse()
	// We don't run it here because this is not a main function and
	// the testing suite has already parsed the flags.
}
```

2020-06-03 07:01 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	flag.Parse()
исправить

2020-06-03 07:01 UTC, Antonboom commented on hw11_telnet_client/main.go
> +		log.Fatalf("Expected to have at least 3 arguments, but got %d", argsCount)
пользователю нужно выдать, что ожидалось 2 аргумента
а то с толку собьете

2020-06-03 07:01 UTC, Antonboom commented on hw11_telnet_client/telnet.go
> +	writer := bufio.NewWriter(out)
не подошла бы тут `io.Copy`?

2020-06-03 07:14 UTC, merged

2020-06-03 11:32 UTC, Antonboom commented
10 / 10