HW 12,13,14,15
JokeTrue/otus-golang pull request #17
Opened 2020-06-08 17:37 UTC by JokeTrue

2020-06-15 12:43 UTC, farir1408 requested changes

2020-06-15 12:43 UTC, farir1408 commented on hw12_13_14_15_calendar/config/init.go
> +package config
Давайте разделим файл конфигурации и гошный код для работы с конфигом. Напрмиер этот пакет можно унести в /internal/pkg/config. Я бы ещё рекомендовал сделать отдельную структуру для конфига, которая затем может быть прокинута в любые другие пакеты проекта. А вот инициализация конфига - это уже второй вопрос, и его можно делать с помощью viper.

2020-06-15 12:43 UTC, farir1408 commented on hw12_13_14_15_calendar/database.env
> +POSTGRES_USER=otus
Лучше вынести это в отдельную директорию типа build и там хранить ещё компоуз файл.

2020-06-15 12:43 UTC, farir1408 commented on hw12_13_14_15_calendar/event/delivery/grpc/handlers.go
> +package grpc
Это часть следующего дз.

2020-06-15 12:43 UTC, farir1408 commented on hw12_13_14_15_calendar/event/delivery/http/handlers.go
> +package http
Это Вы решили сделать дополнительно? по заданию http ручка должна быть одна https://github.com/OtusGolang/home_work/blob/master/hw12_13_14_15_calendar/docs/12_README.md#4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B3%D0%BE-http-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0

2020-06-15 12:43 UTC, farir1408 commented on hw12_13_14_15_calendar/event/repository/psql/event.go
> +	db *gorm.DB
По заданию использование орм запрещено.

2020-06-15 12:46 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.

В ДЗ выполнено многое из будущих заданий, это слегка сбивает. ДЗ выполнено слегка не по заданию: http ручка, и использование gorm. 

Если есть какие-то вопросы, можете написать мне в слак.

2020-06-22 06:36 UTC, JokeTrue commented
@farir1408 Правки готовы

2020-06-23 09:08 UTC, farir1408 approved these changes

2020-06-23 09:08 UTC, farir1408 commented on hw12_13_14_15_calendar/config/config.yaml
> +  path: "."
Можно добавить уровень логирования.

2020-06-23 09:08 UTC, farir1408 commented on hw12_13_14_15_calendar/database/database.go
> +	CREATE TABLE IF NOT EXISTS events
Этот код надо вынести в миграцию, например в /migrations/0001_init.sql.

2020-06-23 09:08 UTC, farir1408 commented on hw12_13_14_15_calendar/event/usecase.go
> +type UseCase interface {
Интерфейс не должен лежать в одном пакете с реализацией. Кладите его туда, где его используете.

2020-06-23 09:08 UTC, farir1408 commented on hw12_13_14_15_calendar/event/usecase/usecase.go
> +type EventUseCase struct {
По сути это бизнес-логика календаря, лучше назвать как-то типа CalendarCore, или просто Calendar.

2020-06-23 09:09 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.

Хорошая работа, предлагаю ещё посмотреть на пример того, как структурировать пакеты: https://github.com/golang-standards/project-layout

Принято 10/10. (миграции добавьте обязательно)

2020-06-23 09:38 UTC, merged