HW4 is completed
JokeTrue/otus-golang pull request #7
Opened 2020-03-29 19:21 UTC by JokeTrue

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-30 14:31 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/88625/6597/

Здравствуйте!

В целом все отлично. Принято будет, как уберете O(n) в кэше.

6 / 10

2020-03-30 14:31 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +		lItem := c.queue.Search(key)
O(n) нехорошо

2020-03-30 14:31 UTC, Antonboom commented on hw04_lru_cache/list.go
> +func (l list) Search(v interface{}) *listItem {
Этого метода можно избежать, если внимательнее читать README:
```
Элемент кэша должен хранить в себе ключ, по которому он лежит в словаре, и само значение. Для чего это нужно понятно из алгоритма работы кэша.
```

2020-03-30 14:31 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +			c.Set(Key('A' + i), i)
Тест проверяет размер очереди.

Хорошо бы еще проверить перемещение элементов внутри нее (подергать несколько (>1) раз разные ключи и чекнуть, что вытолкнулся наименее часто используемый)

2020-03-30 16:46 UTC, JokeTrue commented
Учел все пожелания - запушил правки. 

@Antonboom

2020-03-31 10:46 UTC, Antonboom approved these changes
Что-то вы перемудрили. Внимательнее читайте README.

**Ожидалось:**
```
key string
cacheItem{key, value}
map<key, cacheItem>
list<cacheItem>
```

При set/get: key -> map -> item.value.
При работе со списком: listItem -> cacheItem (-> key -> del map[key], если нужно).

**У вас получилось:**
```
key string
cacheItem{listItem, value}
map<key, cacheItem>
list<key>
```

В общем, связано, но наоборот :)
А так как названия остались для ожидаемого варианта, то получается путаница.

Непринципиально.

Принято
10 / 10

2020-03-31 10:46 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	var cacheKey *listItem
Почему это `cacheKey`, если ключ кэша - строка?

2020-03-31 10:50 UTC, merged